#include "compute/ray.comp"
#include "compute/interval.comp"
#include "compute/random.comp"


bool Metal_scatter(Metal metal, Ray ray, inout HitRecord record) {
    vec3 reflected = reflect(ray.direction, record.normal);
    reflected = normalize(reflected + metal.fuzz * Random_vec3_unitLength());
    record.scattered_ray = Ray_new(record.coord, reflected);
    record.attenuation = metal.albedo;
    return dot(reflected, record.normal) > 0.0f;
}
