#include "compute/ray.comp"


struct HitRecord {
    vec3 coord;
    vec3 normal;
    float alpha;
    bool front_face;

    bool has_scattered;
    vec4 attenuation;
    Ray scattered_ray;
};


void HitRecord_setFaceNormal(inout HitRecord record, Ray ray, vec3 outward_normal) {
    record.front_face = dot(ray.direction, outward_normal) < 0;
    record.normal = normalize(record.front_face ? outward_normal : -outward_normal);
}
