#ifndef SHADERS_COMPUTE_MACROS_H_
#define SHADERS_COMPUTE_MACROS_H_

#define MAX_IFRAMES     10
#define MAX_OBJECTS     10
#define MAX_MATERIALS   10
#define MAX_VERTICES    10
#define MAX_TRIANGLES   100

#ifndef MAX_RECURSION_DEPTH
#define MAX_RECURSION_DEPTH 32
#endif

#endif
